language: node_js
node_js:
  - "11"
cache:
  directories:
    - node_modules
script:
  - yarn test
deploy:
  provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_TOKEN
  skip_cleanup: true
  on:
    tags: true
  branches:
    only: master