export default [
  { id: 'Treenity', label: 'Treenity', depth: 0, more: true, itemHeader: true, itemFooter: true },
  { id: 'src', label: 'src', depth: 1, itemFooter: true, itemHeader: true },
  { id: 'components', label: 'components', depth: 2 },
  { id: 'grid', label: 'grid', depth: 3 },
  { id: 'gridIndex', label: 'index.js', depth: 4, noChildren: true },
  { id: 'button', label: 'button', depth: 3 },
  { id: 'buttonIndex', label: 'index.js', depth: 4, noChildren: true },
  { id: 'icon', label: 'icon', depth: 3 },
  { id: 'iconIndex', label: 'index.js', depth: 4, noChildren: true },
  { id: 'checkbox', label: 'checkbox', depth: 3 },
  { id: 'checkboxIndex', label: 'index.js', depth: 4, noChildren: true },
  { id: 'actions', label: 'actions', depth: 2 },
  { id: 'actionsIndex', label: 'index.js', depth: 3, noChildren: true },
  { id: 'tests', label: 'tests', depth: 1 },
  { id: 'testsIndex', label: 'index.js', depth: 2, noChildren: true },
  { id: 'storybook', label: 'storybook', depth: 1 },
  { id: 'storybookIndex', label: 'index.js', depth: 2, noChildren: true },
  { id: 'config', label: 'config', depth: 1 },
  { id: 'babel', label: 'babel', depth: 2 },
  { id: 'webpack', label: 'webpack', depth: 3, more: true },
  { id: 'webpackIndex', label: 'index.js', depth: 4, noChildren: true },
  { id: 'other', label: 'other', depth: 1, noChildren: true },
];
